name: Packagist update

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Packagist update
        run: curl -XPOST -H "content-type:application/json" "https://packagist.org/api/update-package?username=danniehansenwe&apiToken=$PACKAGIST_API_TOKEN" -d'{"repository":{"url":"https://github.com/blueprinting/backend"}}'
